version: '3'

services:

  # MySQL server
  mysql:
    image: percona
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=tutorial
      - MYSQL_DATABASE=tutorial
    volumes:
      - mysql_volume:${MYSQL_DATA_DIR}

  # phpMyAdmin
  phpmyadmin:
    build:
      context: services/phpmyadmin
      dockerfile: Dockerfile.phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - DEBUG
    ports:
      - 80:80

volumes:
  mysql_volume:
