version: '3'

services:

  # NGINX proxy for virtual hosts inside docker
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT_TO_EXPOSE}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # MySQL server
  mysql:
    build:
      context: services/mysql
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=imbo
      - MYSQL_PASSWORD=imbo
      - MYSQL_DATABASE=imbo
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - ${MYSQL_PORT_TO_EXPOSE}:3306

  # phpMyAdmin
  phpmyadmin:
    build:
      context: services/phpmyadmin
      dockerfile: Dockerfile.phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.local

volumes:
  mysql_volume:
  redis_volume:
