# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.provider "virtualbox" do |v|
      v.memory = 4000
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    config.winrm.timeout = 1800

    config.vm.define "dockertutorial" do |node|

        node.vm.box = "ubuntu/focal64"
        node.vm.boot_timeout = 1800

        node.vm.network "forwarded_port", guest: 80, host: 80 #http
        node.vm.network "forwarded_port", guest: 8080, host: 8080 #http
        node.vm.network "forwarded_port", guest: 3306, host: 3306 #mysql
        node.vm.network "forwarded_port", guest: 3307, host: 3307 #mysql

        node.vm.hostname = "dockertutorial.local"

        node.vm.synced_folder "../tutorial", "/dockertutorial"

        node.vm.provision :shell, path: "provision.sh"
        node.vm.provision :shell, path: "up.sh", run: "always"

        node.hostmanager.aliases = [
            "dockertutorial.local",
            "phpmyadmin.dockertutorial.local",
            "nginx.dockertutorial.local",
            "apifoo.dockertutorial.local",
            "apibar.dockertutorial.local",
            "myapp.dockertutorial.local",
        ]


    end



end
