version: '3'

services:

  # NGINX proxy for virtual hosts inside docker
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT_TO_EXPOSE}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # API FOO
  apifoo:
    build:
      context: services/apifoo
      dockerfile: Dockerfile.apifoo
    environment:
      - VIRTUAL_HOST=apifoo.dockertutorial.local

  # API BAR
  apibar:
    build:
      context: services/apibar
      dockerfile: Dockerfile.apibar
    volumes:
      - ./services/apibar/code:/api
    environment:
      - VIRTUAL_HOST=apibar.dockertutorial.local

volumes:
  mysql_volume:
  redis_volume:
