version: '3'

services:

  # MySQL server
  mysql:
    image: percona
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=tutorial
      - MYSQL_DATABASE=tutorial
    volumes:
      - mysql_volume:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    build:
      context: services/phpmyadmin
      dockerfile: Dockerfile.phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 80:80

volumes:
  mysql_volume:
